### PR TITLE
Fix React Router Framework Support

### PR DESCRIPTION
**Pull request by 0ctan33**
Hi Alex!

We use React Compiler with RRv7 as a Framework. This is working for RR both locally and when deployed in a worker environment but is untested for the other frameworks. It's a bit of a mess but I tried to update the readme with some working code examples as well for reference.

'use no memo' was added as the compiler kept erroring out. This might just be an issue with our Vite config. https://react.dev/learn/react-compiler#something-is-not-working-after-compilation

React Router also has two versions, one as a library using BrowserRouter & one as a framework. This is working for the Framework version.

### CODE REVIEW

**Review by enszrlu — CHANGES_REQUESTED** [review]
Looks great @0ctan33 ! Thanks for your contribution! I will test it on other libraries over the weekend. 

Only thing I am not happy using 'use no memo' everywhere. When I tested this without 'use no memo' on initial react router framework setup, I did not have any issues. 

Would you be able to try again without 'use no memo' to understand if you can fix it on your vite config? I am not 100% sure what was the error without it, so not able to suggest anything at the moment.

**Comment by 0ctan33** [comment]
@enszrlu we use the react compiler beta with react v18 (https://react.dev/learn/react-compiler). 

NextStepContext seems to be incompatible with the compiler due to some issues with hooks. I haven’t had the chance to see why it errors yet so I think for now it’s easier to just bail out of the compiler with 'use no memo' until it can be looked at given the compiler is in beta. I think the same error would occur when using the compiler on a different framework too.

This is the error for reference which seems to be in setCurrentStep: 

```
Invalid hook call. Hooks can only be called inside of the body of a function component. This could happen for one of the following reasons:
1. You might have mismatching versions of React and the renderer (such as React DOM)
2. You might be breaking the Rules of Hooks
3. You might have more than one copy of React in the same app
See https://reactjs.org/link/invalid-hook-call for tips about how to debug and fix this problem.
TypeError: Cannot read properties of null (reading 'useMemo')
    at Object.useMemo (\NextStep-RR\node_modules\.pnpm\react@18.3.1\node_modules\react\cjs\react.development.js:1650:21)
    at Module.c (\NextStep-RR\node_modules\.pnpm\react-compiler-runtime@19.0.0-beta-201e55d-20241215_react@18.3.1\node_modules\react-compiler-runtime\src\index.ts:31:22)
    at NextStepProvider (\NextStep-RR\dist\NextStepContext.js:29:13)
```

Additionally, the react-compiler-runtime package needs to be added as a dev dependency for React versions earlier than v19 for us / anyone using the compiler to be able to run this locally without 'use no memo'.

I've removed the use no memo from all files apart from NextStepContext & the react-router adapter and added the required dev dependency for this to work when using the React Compiler.

**Review by enszrlu — APPROVED** [review]
Looks great! Thanks.

**Comment by enszrlu** [comment]
@0ctan33 Just one question about wrapping the app in react-router. I think it is best to wrap outlet with both provider and NextStep rather than wrapping only with provider then wrapping individual roots with NextStep. I have updated the readme like this. Let me know if you have any doubt. 

Also reach me out on somewhere so I have your contact as well for discussions :)

**Comment by enszrlu** [comment]
@0ctan33 also you can pass the adapter like this to avoid ssr issues when NextStep used in ssr pages. 

<NextStep navigationAdapter={useReactRouterAdapter} steps={steps}>

**Comment by 0ctan33** [comment]
hmm for us I think it would be best to do it on a per route basis because each block of routes has a different set of tours. Might be more of an edge case & I agree that wrapping main outlet with both is probably better for most users. 

Our intended implementation would be checking users onboarding status for a each route in the react router loader and then pulling the steps from api if the user hasn't seen the tour yet

**Comment by enszrlu** [comment]
> hmm for us I think it would be best to do it on a per route basis because each block of routes has a different set of tours. Might be more of an edge case & I agree that wrapping main outlet with both is probably better for most users. 
> 
> Our intended implementation would be checking users onboarding status for a each route in the react router loader and then pulling the steps from api if the user hasn't seen the tour yet

You can have one steps object that merges tours for each route. Then only wrap the main app with NextStep.

You would still control your logic with useNextStep hook in individual routes.

Wrapping each route is also fine, but I prefer wrapping the app to avoid repeat wraps.

**Pull request merged**
